ToDo/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^todo_with_sqlite/', include('todo_with_sqlite.urls', namespace="todo_with_sqlite")),

   
]

todo_with_sqlite/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^add_to_db/$', views.add_to_db, name='add_to_db'),
	url(r'^see_all_tasks/$', views.see_all_tasks, name='see_all_tasks'),	
	url(r'^see_one_task/$', views.see_one_task, name='see_one_task'),
	url(r'^del_all_tasks/$', views.del_all_tasks, name='del_all_tasks'),
	url(r'^del_one_task/$', views.del_one_task, name='del_one_task'),

	
]

todo_with_sqlite/models.py
from django.db import models
from django.forms import ModelForm
from django import forms
import json

class ToDodb(models.Model):
	number_of_task = models.CharField(max_length=500)
	name_of_task = models.CharField(max_length=100)
	deadline_of_task = models.CharField(max_length=10)
	importance = models.IntegerField()
	description = models.CharField(max_length=500)
	def __str__(self): 	
		return ' '.join([self.number_of_task, self.name_of_task])

class ToDodbForm(ModelForm):
	class Meta:
		model = ToDodb
		fields = ['number_of_task', 'name_of_task', 'deadline_of_task', 'importance', 'description']

class Get_task_Form(forms.Form):
	number_of_task = forms.CharField(label='number of task', max_length=100)

todo_with_sqlite/views.py
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.shortcuts import render
from django.http import HttpResponseRedirect
import json
import re

from .models import ToDodb, ToDodbForm, Get_task_Form



def index(request):
	return render(request, 'todo_with_sqlite/index.html')
	

def add_to_db(request):
	
	
	if request.method == 'POST':
		
		form = ToDodbForm(request.POST)
	
		if form.is_valid():			
			new_task = form.save()  
			       						
			return HttpResponseRedirect('/todo_with_sqlite')


	else:
		form = ToDodbForm()

	return render(request, 'todo_with_sqlite/data_entry.html', {'form': form})

def see_all_tasks(request):
	a = ToDodb.objects.all()
	context =  {'list_of': a}

	return render(request, 'todo_with_sqlite/all_tasks.html', context)
	

def see_one_task(request):
	all_tasks = ToDodb.objects.all()
	if request.method == 'POST':
		
		form = Get_task_Form(request.POST)
		
		if form.is_valid():
			data = form.cleaned_data['number_of_task']	
			a = ToDodb.objects.get(number_of_task = data)		
					       						
			return HttpResponse("<html><head></head><body><ul><li>'%s'</li></ul></body></html>"% a)


	else:
		form = Get_task_Form()

	context =  {'list_of': all_tasks, 'form': form}

	return render(request, 'todo_with_sqlite/see_one_task.html', context)

def del_all_tasks(request):
	ToDodb.objects.all().delete()

	return HttpResponse (ToDodb.objects.all())

def del_one_task(request):
	all_tasks = ToDodb.objects.all()
	
	if request.method == 'POST':
		
		form = Get_task_Form(request.POST)
		
	
		if form.is_valid():
			a = form.cleaned_data['number_of_task']	
			ToDodb.objects.filter(number_of_task=a).delete()		
					       						
			return HttpResponseRedirect('/todo_with_sqlite')


	else:
		form = Get_task_Form()

	context =  {'list_of': all_tasks, 'form': form}

	return render(request, 'todo_with_sqlite/del_one_task.html', context)

todo_with_sqlite/templates/todo_with_sqlite/all_tasks.html
<html>
<head>
    <title></title>
	

</head>
<body>
    <h1>Your tasks:</h1>

	{% for a in list_of %}
		<li>{{ a }}</li>
	{% endfor %}
	

	<br>
	<br>
	<a href="{% url 'todo_with_sqlite:index' %}">Back to options</a>
    
</body>
</html>

todo_with_sqlite/templates/todo_with_sqlite/data_entry.html
<html>
<head>
    <title></title>
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'todo_with_sqlite/data_entry.css' %}" />

</head>
<body>
	<div class="wrapper">
		<h2>Fill out these fields:</h2>
		<form action="/todo_with_sqlite/add_to_db/" method="post" class="add_data1">
		{% csrf_token %}
		{{ form }}
		<input type="submit" value="Submit" />
		<br>
		<br>
		<a href="{% url 'todo_with_sqlite:index' %}">Back to options</a>
    </div>
</form>
</body>
</html>

todo_with_sqlite/templates/todo_with_sqlite/del_one_task.html
<html>
<head>
    <title></title>
	
</head>
<body>
    <h1>Your tasks:</h1>	
		{% for a in list_of %}
			<li>{{ a }}</li>
		{% endfor %}
	<h2>So, make a decision what task you want to remove and write it below</h2>

	<form action="/todo_with_sqlite/del_one_task/" method="post" class="add_data">
    	{% csrf_token %}
    	{{ form }}
    	<input type="submit" value="Submit" />
	</form>		 
	

	<br>
	<br>
	<a href="{% url 'todo_with_sqlite:index' %}">Back to options</a>
    
</body>
</html>

todo_with_sqlite/templates/todo_with_sqlite/index.html
<html>
<head>
</head>
<body>
	<a href="add_to_db">Add new task</a>
	<br>
	<br>
	<a href="see_all_tasks">See all tasks</a>
	<br>	
	<br>
	<a href="see_one_task">See one task</a>
	<br>
	<br>
	<a href="add">Edit one task</a>
	<br>
	<br>
	<a href="del_one_task">Delit one task</a>
	<br>
	<br>
	<a href="del_all_tasks">Delit all tasks</a>
</body>
</html

todo_with_sqlite/templates/todo_with_sqlite/see_one_task.html
<html>
<head>
    <title></title>
	
</head>
<body>
    <h1>Your tasks:</h1>	
		{% for a in list_of %}
		<li>{{ a }}</li>
		{% endfor %}
	<br>
	<h2>What task do you want to see?</h2>

	<form action="/todo_with_sqlite/see_one_task/" method="post" class="add_data">
    	{% csrf_token %}
    	{{ form }}
    	<input type="submit" value="Submit" />
	</form>		 
	

	<br>
	<br>
	<a href="{% url 'todo_with_sqlite:index' %}">Back to options</a>
    
</body>
</html>